#!/usr/bin/with-contenv bash
PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -g 1000 users
useradd -u 911 -U -d /config -s /bin/false abc
usermod -G users abc

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc


mkdir -p /defaults
chown -R abc:abc /defaults
echo "
User uid:    $(id -u abc) $(stat -c '%U' /defaults)
Group gid:   $(id -g abc) $(stat -c '%G' /defaults)
-------------------------------------
"
