#!/usr/bin/with-contenv bash
PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -g 1000 users
useradd -u 911 -U -d /config -s /bin/false abc
usermod -G users abc

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown -R abc:abc /defaults